algoritmo "pgm09"
// Função : soma de dois numeros digitados pelo usuario
// Autor :   Renato Mdias
// Data : 21/01/2021
// Seção de Declarações 
var
       num1,num2,res:inteiro
inicio

     //requizitando valores para o ususario
      escreval("Digite um valor:")
      leia(num1)
      escreval("Digite outo valor :")
      leia(num2)
      //processamento
      res <- num1+num2
      
      //saida na tela
      escreval("A soma é :",res)

fimalgoritmo
