algoritmo "pgm16"
// Função : calculo de um retangulo
// Autor :  renato m dias
// Data : 21/01/2021
// Seção de Declarações 
var
       res,num1,num2:real
inicio

      //obter informaçoes do usuario
       escreval("Digite o valor da base :")
       leia(num1)
       escreval("Digite a Altura :")
       leia(num2)
       //processamento
       res <- num2 * num2
       
       
       //saida na tela
       escreval("O valor do retangulo é :",res)


fimalgoritmo
