algoritmo "pgm11"
// Função : Multiplicação de dois numeros digitados pelo usuario
// Autor :   Renato Mdias
// Data : 21/01/2021
// Seção de Declarações
var
       num1,num2,res:inteiro
inicio

     // requizitar valorese para o usuario
      escreval("Digite um valor:")
      leia(num1)
      escreval("Digite outo valor :")
      leia(num2)
      //processamento
      res <- num1 * num2
      //resposta
      escreval("A Multiplicação é :",res)

fimalgoritmo
