algoritmo "pgm15"
// Função : ler um valor do teclado e mostrar seu antesesor
// Autor :
// Data : 21/01/2021
// Seção de Declarações
var
         num,res:inteiro
inicio
         // Seção de Comandos
         //requerendo informaçoes
         escreval("Digite um valor:")
         leia(num)
         //atribuição de valor
         res <- num - 1
         //apresenta na tela
         escreval("Seu antesessor é",res)



fimalgoritmo
