algoritmo "pgm12"
// Função : divisão de dois numeros digitados pelo usuario
// Autor :   Renato Mdias
// Data : 21/01/2021
// Seção de Declarações
var
       num1,num2,res:real
inicio

     // requizitar valorese para o usuario
      escreval("Digite um valor:")
      leia(num1)
      escreval("Digite outo valor  :")
      leia(num2)
      //processamento
      res <- num1 / num2
      //resposta na tela
      escreval("A Divisão é :",res)

fimalgoritmo
