algoritmo "pgm20"
// Função :  converte dolar para real
// Autor :   renato
// Data :   22/01/2021
// Seção de Declarações
var
            res,dolar,rea:real
inicio
         // Seção de Comandos
         //recebe valor pelo usuario
         escreval("iforme o valor em dolar")
         leia (dolar)

         //procesamento
         res <-  (dolar * 6.61 )
         //apresenta na tela
         escreval("valor em real é",res)
fimalgoritmo
