algoritmo "pgm37"
// Função :
// Autor :
// Data : 25/01/2021
// Seção de Declarações
var
         a,b,c:real
inicio
         // Seção de Comandos
         // atribui valor a variavel
         a <- 30
         b <-20
         c <- a+b

         // apresenta na tela
         escreval("C",c)
         b <- 10
         escreval("B,C",b,c)
         c <- a+b
         escreval("A,B,C",a,b,c)


fimalgoritmo
