algoritmo "pgm40"
// Função :  atribuição de valores
// Autor :   renato m. dias
// Data : 25/01/2021
// Seção de Declarações
var
         a,b,c:real
inicio
         // Seção de Comandos
         // atribuição
         a <- 10
         b <- a+1
         a <-b+1
         b <- a+1

         //apresnta na tela
         escreval(a)
         a <-b+1
         //apresnta na tela
         escreval(a,b)

fimalgoritmo
