algoritmo "pgm41"
// Função : atribuição de valores
// Autor :  renato m. dias
// Data : 25/01/2021
// Seção de Declarações
var
         x,y,z:real
inicio
         // Seção de Comandos
         //atribuição
         x <- 1
         y <- 2
         z <- Y-X

         //apresnta na tela
         escreval(z)
         x <-5
         Y <-x+z
         //apresnta na tela
         escreval(x,y,z)
fimalgoritmo
